# Generated by Django 5.2.1 on 2025-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_internet_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
