# Generated by Django 5.1.6 on 2025-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_internet_shop', '0002_user_delete_itemcard_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=100, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
