# Generated by Django 5.1.6 on 2025-05-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_internet_shop', '0003_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='USERNAME_FIELD',
        ),
    ]
