# Generated by Django 5.1.6 on 2025-05-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_internet_shop', '0004_rename_name_user_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='set_password',
        ),
    ]
