# Generated by Django 5.1.6 on 2025-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_internet_shop', '0005_rename_password_user_set_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='set_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Эл. Почта'),
            preserve_default=False,
        ),
    ]
